### ISSUE TITLE
Preserve type attribute of KGML relation elements in SBML

### ISSUE THREAD

**Issue by KallyopeBio** [draeger-lab/KEGGtranslator#3]
Currently, the KEGGtranslator converts relations in KGML documents into Transitions in SBML documents. However, the SBML Transitions do not preserve the type of the KEGG relation (GErel, PPrel, PCrel, ECrel, or mapping). Downstream software (reading the SBML) may only want to consider particular classes of transitions (e.g., those deriving from GErel, PPrel, and PCrel relations) and ignore others. 

This is a feature request to add an annotation or note to Transition elements in the SBML to preserve the type of the relation from KGML.

**Comment by draeger** [comment]
For this request it will be necessary to identify a way how this information can be best stored. It seems an annotation could potentially work, but there is no direct field for storing this information in SBML. @KallyopeBio, is there a specific place you have in mind where you expect to find this information?

**Comment by KallyopeBio** [comment]
Actually, this request can be closed. The information I need is already in the SBML output from KEGGtranslator. Reading over the source code, and then checking against actual examples, I see that the subtype of the relation (which provides more detail actually than the type) is encoded in the SBO term of the annotation of the Transition. This is done via the mapping in file SBOMapping.java.
