### ISSUE TITLE
Possible to recover subcellular location?

### ISSUE THREAD

**Issue by KallyopeBio** [draeger-lab/KEGGtranslator#6]
KEGG pathways include (in an albeit obscure way) information about where reactions and relations occur in the cell (e.g., intercellular reactions that occur entirely in the cell, or ligand-receptor interactions that occur outside the cell and on the membrane). Is there any way for the KEGGtranslator to extract that info and encode it in the SBML?

**Comment by KallyopeBio** [comment]
Well, the KEGG _pathways_ include subcellular localization (for instance, for signaling pathways), but it looks like the KGML files _do not_? KEGG creates its pathway images using their proprietary KegSketch algorithm, but the output from that procedure seems to include information that's not even implicitly encoded in the KGMLs. If the subcellular location information is not even resident in the KGML files, then the solution to this problem will lie far outside the scope of the KEGGtranslator. But I figured I'd ask the experts here, anyway, in case I'm missing something.

**Comment by draeger** [comment]
@KallyopeBio, as you correctly state in your second post on this issue, KEGG does know where processe happen, but, unfortunately, this information is only given in (some) pathway images. The KGML entirely lacks this information. One would need to do image processing for this and this is complicated to do. Furthermore, not all map images contain compartment boundaries. Hence, there is not much KEGGtranslator could do in this regard.
